language: bash
services: docker

before_script:
  - env | sort
  - repo="arpitjindal1997/TelegramAircelBot"
  - image="$repo:latest"

script:
  - docker build -t $image .

after_script:
  - docker images
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push $repo
